# Generated by Django 4.2 on 2024-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_gate',
            field=models.CharField(default='01', max_length=10),
        ),
    ]
