# Generated by Django 4.2 on 2024-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_flight_departure_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_status',
            field=models.CharField(default='ON TIME', max_length=10),
        ),
    ]
